spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://dpg-d7v3tbtckfvc739sr550-a:5432/bd_sw_zgo7
spring.datasource.username=bd_sw_zgo7_user
spring.datasource.password=ACJtEppm6IUNwcGblfEHhBVTNfE97Mt3cl

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
server.servlet.session.timeout=300s